In [1]:
# Import dependencies
import pandas as pd
import requests
import numpy as np
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [2]:
# Read data from csv
filepath = 'all_time_traffic_incidents_20240119.csv'
df = pd.read_csv(filepath)

In [3]:
# Check df
df.head()

,Traffic Report ID,Published Date,Issue Reported,Location,Latitude,Longitude,Address,Status,Status Date
0,121E4F6B2D93D3F508359C8700406A1B992733AF_16597...,2022-08-05 21:37:14,Traffic Hazard,POINT (0 0),0.000000,0.000000,tra,ARCHIVED,2022-08-05 21:50:03
1,B852035718A45A6479B38C26FA96B28B0C9A8A56_16615...,2022-08-26 21:05:01,Traffic Hazard,POINT (0 0),0.000000,0.000000,900 S FM 973,ARCHIVED,2022-08-26 21:35:03
2,B7CA5DF711D07BA6D03B6EF004402A6594C77CD6_16622...,2022-09-04 04:16:02,Collision,POINT (0 0),0.000000,0.000000,12009 W US 290 HWY,ARCHIVED,2022-09-04 05:40:03
3,5F5898E4726001663BA5A126B313B03B1AED3F07_16631...,2022-09-14 15:14:19,Crash Urgent,POINT (-97.711561 30.307396),30.307396,-97.711561,4900 N Ih 35 Nb,ARCHIVED,2022-09-14 15:30:04
4,3791C82875F2B544CEFA8FBE35109575B1431A30_16631...,2022-09-14 13:50:59,Traffic Hazard,POINT (-97.820007 30.233228),30.233228,-97.820007,4953-4973 W Us 290 Hwy Eb,ARCHIVED,2022-09-14 14:10:02

In [4]:
# Combine all crash and collision incident types
df.loc[df['Issue Reported'].isin(['Crash Urgent',
                                'Crash Service',
                                'Collision',
                                'Collision With Injury',
                                'Collision/Leaving Scene',
                                'Collision/Private Property']),'Issue Reported'] = 'Collision/Crash'

# Extract only crashes & collisions
df_c = df.loc[df['Issue Reported']=='Collision/Crash'].drop(columns=['Issue Reported','Location', 'Status', 'Status Date',
                                                                     'Address','Traffic Report ID'])

In [5]:
df_c.head()

         Published Date   Latitude  Longitude
2   2022-09-04 04:16:02   0.000000   0.000000
3   2022-09-14 15:14:19  30.307396 -97.711561
5   2022-09-13 13:02:12  30.439546 -97.780078
9   2022-09-13 22:29:31  30.497216 -97.595372
10  2022-09-14 15:22:24  30.423104 -97.668259